-- 01_ddl_schema.sql
CREATE SEQUENCE seq_cust START WITH 1;
CREATE SEQUENCE seq_order START WITH 1;
CREATE SEQUENCE seq_item START WITH 1;

CREATE TABLE customers (
    cust_id NUMBER PRIMARY KEY,
    name VARCHAR2(100),
    email VARCHAR2(100)
);

CREATE TABLE orders (
    order_id NUMBER PRIMARY KEY,
    cust_id NUMBER REFERENCES customers(cust_id),
    order_date DATE,
    status VARCHAR2(20)
);

CREATE TABLE order_items (
    item_id NUMBER PRIMARY KEY,
    order_id NUMBER REFERENCES orders(order_id),
    product_name VARCHAR2(100),
    quantity NUMBER,
    price NUMBER
);

-- Таблица для хранения истории изменений с JSON
CREATE TABLE operation_logs (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR2(30),
    record_id NUMBER,
    operation_type VARCHAR2(10),
    operation_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    old_value_json CLOB,
    reverted CHAR(1) DEFAULT 'N'
);